CREATE TABLE "S_GUIA"."CLAVE" 
   (	"VCODUSUARIO" VARCHAR2(15 BYTE), 
	"NCODCLAVE" NUMBER(10,0), 
	"VPASS" VARCHAR2(200 BYTE), 
	"NESTADO" NUMBER(4,0), 
	"VFLAG_TEMP" VARCHAR2(1 BYTE), 
	"VRESCRE" VARCHAR2(15 BYTE), 
	"DFECCRE" DATE, 
	"VRESACT" VARCHAR2(15 BYTE), 
	"DFECACT" DATE, 
	"VFLAG_CLAVE_INVALIDA" VARCHAR2(1 BYTE)
   ) 

COMMENT ON COLUMN "S_GUIA"."CLAVE"."VCODUSUARIO" IS 'CODIGO DE USUARIO';
COMMENT ON COLUMN "S_GUIA"."CLAVE"."NCODCLAVE" IS 'CODIGO DE CLAVE';
COMMENT ON COLUMN "S_GUIA"."CLAVE"."VPASS" IS 'CLAVE ENCRIPTADA';
COMMENT ON COLUMN "S_GUIA"."CLAVE"."NESTADO" IS 'ESTADO DEL REGISTRO';
COMMENT ON COLUMN "S_GUIA"."CLAVE"."VFLAG_TEMP" IS 'INDICADOR DE CLAVE TEMPORAL';
COMMENT ON COLUMN "S_GUIA"."CLAVE"."VRESCRE" IS 'USUARIO CREACION DEL REGISTRO';
COMMENT ON COLUMN "S_GUIA"."CLAVE"."DFECCRE" IS 'FECHA DE CREACION DEL REGISTRO';
COMMENT ON COLUMN "S_GUIA"."CLAVE"."VRESACT" IS 'USUARIO ACTUALIZACION DEL REGISTRO';
COMMENT ON COLUMN "S_GUIA"."CLAVE"."DFECACT" IS 'FECHA DE ACTUALIZACION DEL REGISTRO';
COMMENT ON COLUMN "S_GUIA"."CLAVE"."VFLAG_CLAVE_INVALIDA" IS 'FLAG INDICADOR DE CLAVE INVALIDA';


   