CREATE TABLE SISTEMA_MODULO
(
  NCODSISTEMA  NUMBER(4) NOT NULL,
  NCODMODULO   NUMBER(10) NOT NULL,
  VDESCRIPCION VARCHAR2(40) NOT NULL,
  NESTADO      NUMBER(4),
  VRESCRE      VARCHAR2(15),
  DFECCRE      DATE,
  VRESACT      VARCHAR2(15),
  DFECACT      DATE
);

ALTER TABLE SISTEMA_MODULO
ADD CONSTRAINT PK_SISTEMA_MODULO PRIMARY KEY (NCODSISTEMA, NCODMODULO);

ALTER TABLE SISTEMA_MODULO
ADD CONSTRAINT FK_SISTEMA_MODULO_1 FOREIGN KEY (NCODSISTEMA)
REFERENCES SISTEMA (NCODSISTEMA);

COMMENT ON COLUMN "S_GUIA"."SISTEMA_MODULO"."NCODSISTEMA" IS 'CODIGO DEL  SISTEMA';
COMMENT ON COLUMN "S_GUIA"."SISTEMA_MODULO"."NCODMODULO" IS 'CODIGO DEL  MODULO';
COMMENT ON COLUMN "S_GUIA"."SISTEMA_MODULO"."VDESCRIPCION" IS 'DESCRIPCION DEL SISTEMA MODULO';
COMMENT ON COLUMN "S_GUIA"."SISTEMA_MODULO"."NESTADO" IS 'ESTADO DEL SISTEMA MODULO, ACTIVO INACTIVO';
COMMENT ON COLUMN "S_GUIA"."SISTEMA_MODULO"."VRESCRE" IS 'USUARIO CREACION';
COMMENT ON COLUMN "S_GUIA"."SISTEMA_MODULO"."DFECCRE" IS 'FECHA CREACION';
COMMENT ON COLUMN "S_GUIA"."SISTEMA_MODULO"."VRESACT" IS 'USUARIO MODIFICACION';
COMMENT ON COLUMN "S_GUIA"."SISTEMA_MODULO"."DFECACT" IS 'USUARIO MODIFICACION';
  
INSERT INTO SISTEMA_MODULO (NCODSISTEMA, NCODMODULO, VDESCRIPCION, NESTADO, VRESCRE, DFECCRE, VRESACT, DFECACT)
VALUES (46, 1, 'CONTROL DE SEGURIDAD', 0, 'SEGADMIN', SYSDATE, 'SEGADMIN', SYSDATE);


  
  
  