ALTER TABLE S_GUIA.SISTEMA ADD VFLAG_NIVEL VARCHAR2(1);
ALTER TABLE S_GUIA.SISTEMA ADD VRESCRE VARCHAR2(15);
ALTER TABLE S_GUIA.SISTEMA ADD DFECCRE DATE;
ALTER TABLE S_GUIA.SISTEMA ADD VRESACT VARCHAR2(15);
ALTER TABLE S_GUIA.SISTEMA ADD DFECACT DATE;


INSERT INTO SISTEMA (NCODSISTEMA, VDESCRIPCION, VABREVIATURA, NESTADO, VPROGRAMA, VFLAG_NIVEL, VRESCRE, DFECCRE, VRESACT, DFECACT)
VALUES (46, 'SISTEMA DE SEGURIDAD', 'SEG', 0, 'JAVA', '2', 'SEGADMIN', SYSDATE, 'SEGADMIN', SYSDATE);

COMMENT ON COLUMN "S_GUIA"."SISTEMA"."VFLAG_NIVEL" IS 'FLAG INDICADOR DEL NIVEL DEL SISTEMA';
COMMENT ON COLUMN "S_GUIA"."ACCESOS"."VRESCRE" IS 'USUARIO CREACION DEL REGISTRO';
COMMENT ON COLUMN "S_GUIA"."ACCESOS"."DFECCRE" IS 'FECHA DE CREACION DEL REGISTRO';
COMMENT ON COLUMN "S_GUIA"."ACCESOS"."VRESACT" IS 'USUARIO ACTUALIZACION DEL REGISTRO';
COMMENT ON COLUMN "S_GUIA"."ACCESOS"."DFECACT" IS 'FECHA DE ACTUALIZACION DEL REGISTRO';