CREATE OR REPLACE VIEW VW_FORMULARIO_MODULO AS
SELECT F.NCODSISTEMA,
             F.NCODMODULO,
             F.NCODFORMULARIO,
             NVL(F.VDESCRIPCION, '') VDESCRIPCION,
             F.NESTADO,
             F.NCODFORMULARIO_PADRE,
             F.NNIVEL_FORMULARIO,
             F.NORDEN_FORMULARIO,
             F.VURL_FORMULARIO,
             UPPER(NVL(P.VDESCRIPCION, '')) VESTADONOMBRE,
             UPPER(S.VDESCRIPCION) VSISTEMANOMBRE,
             UPPER(M.VDESCRIPCION) VMODULONOMBRE,
             F.VRESCRE,
             F.DFECCRE,
             F.VRESACT,
             F.DFECACT,
            (UPPER(F.VDESCRIPCION) || UPPER(S.VDESCRIPCION)|| UPPER(M.VDESCRIPCION || P.VDESCRIPCION || F.VURL_FORMULARIO || F.NCODMODULO || F.NCODFORMULARIO)) VBUSCAR
        FROM S_GUIA.SISTEMA_MODULO_FORM F
        LEFT JOIN S_GUIA.SISTEMA_PARAMETRO P ON P.VCODPARAMETRO = 'ESTADO'
                                            AND P.NID = F.NESTADO
       INNER JOIN S_GUIA.SISTEMA S ON F.NCODSISTEMA = S.NCODSISTEMA
       INNER JOIN S_GUIA.SISTEMA_MODULO M ON F.NCODSISTEMA = M.NCODSISTEMA
                                         AND F.NCODMODULO = M.NCODMODULO
      WHERE S.NESTADO = 0;