CREATE OR REPLACE VIEW VW_USUARIO_SISTEMA AS
SELECT UPS.NCODSISTEMA,
         U.VCODUSUARIO,
         U.NESTADO,
         UPPER(S.VDESCRIPCION) VSISTEMANOMBRE,
         NVL(U.VDESCRIPCION,' ') AS VDESCRIPCION,
         NVL(U.NCODFICHA,'0') AS NCODFICHA,
         NVL(U.NCODAREA,'0') AS NCODAREA,
         P.VDESCRIPCION VESTADONOMBRE,
         UPPER(NVL(A.VDESCRIPCION,' ')) AREA,
         NVL(U.NCODAREA,'0') || '-' || UPPER(NVL(A.VABREVIATURA,' ')) AREAABREV,
         NVL(T.NCODAREA,'0') AREATRAB,
         PS.VDESCRIPCION NOMBREPERFIL,
         decode(T.VCODESTADO, 'EIRC02', 'BAJA', 'ACTIVO') ESTTRAB,
         NVL(T.VDIRELECTRONICA,' ') VDIRELECTRONICA ,
        ( U.VCODUSUARIO || S.VDESCRIPCION || U.VDESCRIPCION || U.NCODFICHA || PS.VDESCRIPCION || P.VDESCRIPCION || U.NCODFICHA || U.NCODAREA || PS.VDESCRIPCION) VBUSCAR
    FROM S_GUIA.USUARIO U
    LEFT JOIN TRABAJADOR T ON U.NCODFICHA = T.NFICHA AND T.IND_EMAIL = 0 AND T.Vcodestado = 'EIRC01'
    LEFT JOIN AREA A ON A.NCODAREA = U.NCODAREA
    INNER JOIN USUARIO_PERFIL_SISTEMA UPS ON UPS.VCODUSUARIO = U.VCODUSUARIO
    INNER JOIN PERFIL_SISTEMA PS ON PS.NCODPERFIL = UPS.NCODPERFIL AND PS.NCODSISTEMA = UPS.NCODSISTEMA
   INNER JOIN S_GUIA.SISTEMA_PARAMETRO P ON P.VCODPARAMETRO = 'ESTADO'
                                        AND P.NID = U.NESTADO
    LEFT JOIN USUARIO_PERFIL_SISTEMA UPS ON U.VCODUSUARIO = UPS.VCODUSUARIO
    LEFT JOIN SISTEMA S ON UPS.NCODSISTEMA = S.NCODSISTEMA
    WHERE S.NESTADO = 0
     GROUP BY UPS.NCODSISTEMA, U.VCODUSUARIO, U.NESTADO, S.VDESCRIPCION, U.VDESCRIPCION,
                                   U.NCODFICHA, U.NCODAREA, P.VDESCRIPCION,A.VDESCRIPCION,A.VABREVIATURA,T.NCODAREA,PS.VDESCRIPCION,
                                   T.VCODESTADO,T.VDIRELECTRONICA

  /*SELECT UPS.NCODSISTEMA,
                             U.VCODUSUARIO,
                             U.NESTADO,
                             UPPER(S.VDESCRIPCION) VSISTEMANOMBRE,
                             U.VDESCRIPCION,
                             U.NCODFICHA,
                             U.NCODAREA,
                             P.VDESCRIPCION VESTADONOMBRE,
                             (S.VDESCRIPCION || U.VDESCRIPCION || U.VCODUSUARIO) VBUSCAR
                             FROM S_GUIA.USUARIO U
                             INNER JOIN S_GUIA.SISTEMA_PARAMETRO P ON P.VCODPARAMETRO = 'ESTADO' AND P.NID = U.NESTADO
                             LEFT JOIN USUARIO_PERFIL_SISTEMA UPS ON U.VCODUSUARIO = UPS.VCODUSUARIO
                             LEFT JOIN SISTEMA S ON UPS.NCODSISTEMA = S.NCODSISTEMA
                             GROUP BY UPS.NCODSISTEMA, U.VCODUSUARIO, U.NESTADO, S.VDESCRIPCION, U.VDESCRIPCION,
                                   U.NCODFICHA, U.NCODAREA, P.VDESCRIPCION*/;
