ALTER TABLE S_GUIA.USUARIO_PERFIL_SISTEMA ADD VRESCRE VARCHAR2(15);
ALTER TABLE S_GUIA.USUARIO_PERFIL_SISTEMA ADD DFECCRE DATE;
ALTER TABLE S_GUIA.USUARIO_PERFIL_SISTEMA ADD VRESACT VARCHAR2(15);
ALTER TABLE S_GUIA.USUARIO_PERFIL_SISTEMA ADD DFECACT DATE;

COMMENT ON COLUMN "S_GUIA"."USUARIO_PERFIL_SISTEMA"."VRESCRE" IS 'USUARIO CREACION DEL REGISTRO';
COMMENT ON COLUMN "S_GUIA"."USUARIO_PERFIL_SISTEMA"."DFECCRE" IS 'FECHA DE CREACION DEL REGISTRO';
COMMENT ON COLUMN "S_GUIA"."USUARIO_PERFIL_SISTEMA"."VRESACT" IS 'USUARIO ACTUALIZACION DEL REGISTRO';
COMMENT ON COLUMN "S_GUIA"."USUARIO_PERFIL_SISTEMA"."DFECACT" IS 'FECHA DE ACTUALIZACION DEL REGISTRO';


INSERT INTO S_GUIA.USUARIO_PERFIL_SISTEMA (NCODPERFIL, NCODSISTEMA, VCODUSUARIO, NESTADO, VRESCRE, DFECCRE, VRESACT, DFECACT)
VALUES (1, 46, 'SEGADMIN', 1, 'SEGADMIN', SYSDATE, 'SEGADMIN', SYSDATE);

