ALTER TABLE S_GUIA.USUARIO
MODIFY VPASS  VARCHAR2(200);

ALTER TABLE S_GUIA.USUARIO
ADD NUMERO_INTENTOS NUMERIC(4);

ALTER TABLE S_GUIA.USUARIO
ADD DFEC_INICIO_VIGENCIA DATE;

ALTER TABLE S_GUIA.USUARIO
ADD DFEC_FIN_VIGENCIA DATE;

ALTER TABLE S_GUIA.USUARIO
ADD VFLAG_CAMBIAR_CLAVE VARCHAR(1);


COMMENT ON COLUMN "S_GUIA"."USUARIO"."NUMERO_INTENTOS" IS 'NUMERO DE INTENTOS DE INGRESO AL SISTEMA';
COMMENT ON COLUMN "S_GUIA"."USUARIO"."DFEC_INICIO_VIGENCIA" IS 'FECHA DE INICIO DE VIGENCIA';
COMMENT ON COLUMN "S_GUIA"."USUARIO"."DFEC_FIN_VIGENCIA" IS 'FECHA DE FIN DE VIGENCIA';
COMMENT ON COLUMN "S_GUIA"."USUARIO"."VFLAG_CAMBIAR_CLAVE" IS 'FLAG INDICADOR SI EL USUARIO DEBE CAMBIAR SU CLAVE';


INSERT INTO USUARIO (VCODUSUARIO, VDESCRIPCION, NESTADO, NCODAREA, DFECCREACION, DFECACTUALIZACION, VRESPONSABLE, VZONA, NCODFICHA, NINDICADOR, VPASS, DFECULTVER, DFECCLAVE, NCONEXION, VSUSTENTACION, VDOC, NUMERO_INTENTOS, DFEC_INICIO_VIGENCIA, DFEC_FIN_VIGENCIA, VFLAG_CAMBIAR_CLAVE)
VALUES ('SEGADMIN', 'COCA ZUMARAN JOSE MANUEL', 1, 313, SYSDATE, SYSDATE, 'SEGADMIN', '', 13958, 0, '$2A$10$AW2G0PKM3A5BIUOQ2YHL1OVDILE1JFENNODCN7HYAYNGILFZ.ZK32', NULL, NULL, 0, 'SEGADMIN', '', 0, NULL, NULL, '0');

