CREATE TABLE PERFIL_ACCION
  (
    NCODPERFIL_ACCION      NUMBER (10) NOT NULL ,
    NCODPERFIL             NUMBER (3) NOT NULL ,
    NCODSISTEMA            NUMBER (4) NOT NULL ,
    NCODACCION_FORMULARIO NUMBER (10) NOT NULL
  ) ;
  
COMMENT ON COLUMN "S_GUIA"."PERFIL_ACCION"."NCODPERFIL_ACCION" IS 'CODIGO DEL REGISTRO PERFIL ACCION';
COMMENT ON COLUMN "S_GUIA"."PERFIL_ACCION"."NCODPERFIL" IS 'CODIGO DEL PERFIL';
COMMENT ON COLUMN "S_GUIA"."PERFIL_ACCION"."NCODSISTEMA" IS 'CODIGO DEL SISTEMA';
COMMENT ON COLUMN "S_GUIA"."PERFIL_ACCION"."NCODACCION_FORMULARIO" IS 'CODIGO DEL REGISTRO ACCION FORMULARIO';
  
ALTER TABLE PERFIL_ACCION ADD CONSTRAINT SEG_PERFIL_ACCION_PK PRIMARY KEY ( NCODPERFIL_ACCION ) ;

ALTER TABLE PERFIL_ACCION ADD CONSTRAINT SEG_PERF_ACC_PER_SISTEMA_FK 
      FOREIGN KEY ( NCODPERFIL, NCODSISTEMA ) REFERENCES PERFIL_SISTEMA ( NCODPERFIL, NCODSISTEMA ) ;
      
ALTER TABLE PERFIL_ACCION ADD CONSTRAINT SEG_PER_ACC_SEG_ACC_FORM_FK 
      FOREIGN KEY ( NCODACCION_FORMULARIO ) REFERENCES ACCION_FORMULARIO ( NCODACCION_FORMULARIO );
      
      INSERT INTO PERFIL_ACCION (NCODPERFIL_ACCION, NCODPERFIL, NCODSISTEMA, NCODACCION_FORMULARIO)
VALUES (280, 1, 46, 81);

INSERT INTO PERFIL_ACCION (NCODPERFIL_ACCION, NCODPERFIL, NCODSISTEMA, NCODACCION_FORMULARIO)
VALUES (281, 1, 46, 16);

INSERT INTO PERFIL_ACCION (NCODPERFIL_ACCION, NCODPERFIL, NCODSISTEMA, NCODACCION_FORMULARIO)
VALUES (282, 1, 46, 15);

INSERT INTO PERFIL_ACCION (NCODPERFIL_ACCION, NCODPERFIL, NCODSISTEMA, NCODACCION_FORMULARIO)
VALUES (283, 1, 46, 14);

INSERT INTO PERFIL_ACCION (NCODPERFIL_ACCION, NCODPERFIL, NCODSISTEMA, NCODACCION_FORMULARIO)
VALUES (284, 1, 46, 13);

INSERT INTO PERFIL_ACCION (NCODPERFIL_ACCION, NCODPERFIL, NCODSISTEMA, NCODACCION_FORMULARIO)
VALUES (285, 1, 46, 20);

INSERT INTO PERFIL_ACCION (NCODPERFIL_ACCION, NCODPERFIL, NCODSISTEMA, NCODACCION_FORMULARIO)
VALUES (286, 1, 46, 19);

INSERT INTO PERFIL_ACCION (NCODPERFIL_ACCION, NCODPERFIL, NCODSISTEMA, NCODACCION_FORMULARIO)
VALUES (287, 1, 46, 18);

INSERT INTO PERFIL_ACCION (NCODPERFIL_ACCION, NCODPERFIL, NCODSISTEMA, NCODACCION_FORMULARIO)
VALUES (288, 1, 46, 17);

INSERT INTO PERFIL_ACCION (NCODPERFIL_ACCION, NCODPERFIL, NCODSISTEMA, NCODACCION_FORMULARIO)
VALUES (289, 1, 46, 24);

INSERT INTO PERFIL_ACCION (NCODPERFIL_ACCION, NCODPERFIL, NCODSISTEMA, NCODACCION_FORMULARIO)
VALUES (290, 1, 46, 23);

INSERT INTO PERFIL_ACCION (NCODPERFIL_ACCION, NCODPERFIL, NCODSISTEMA, NCODACCION_FORMULARIO)
VALUES (291, 1, 46, 22);

INSERT INTO PERFIL_ACCION (NCODPERFIL_ACCION, NCODPERFIL, NCODSISTEMA, NCODACCION_FORMULARIO)
VALUES (292, 1, 46, 21);

INSERT INTO PERFIL_ACCION (NCODPERFIL_ACCION, NCODPERFIL, NCODSISTEMA, NCODACCION_FORMULARIO)
VALUES (293, 1, 46, 32);

INSERT INTO PERFIL_ACCION (NCODPERFIL_ACCION, NCODPERFIL, NCODSISTEMA, NCODACCION_FORMULARIO)
VALUES (294, 1, 46, 31);

INSERT INTO PERFIL_ACCION (NCODPERFIL_ACCION, NCODPERFIL, NCODSISTEMA, NCODACCION_FORMULARIO)
VALUES (295, 1, 46, 30);

INSERT INTO PERFIL_ACCION (NCODPERFIL_ACCION, NCODPERFIL, NCODSISTEMA, NCODACCION_FORMULARIO)
VALUES (296, 1, 46, 29);

INSERT INTO PERFIL_ACCION (NCODPERFIL_ACCION, NCODPERFIL, NCODSISTEMA, NCODACCION_FORMULARIO)
VALUES (297, 1, 46, 12);

INSERT INTO PERFIL_ACCION (NCODPERFIL_ACCION, NCODPERFIL, NCODSISTEMA, NCODACCION_FORMULARIO)
VALUES (298, 1, 46, 11);

INSERT INTO PERFIL_ACCION (NCODPERFIL_ACCION, NCODPERFIL, NCODSISTEMA, NCODACCION_FORMULARIO)
VALUES (299, 1, 46, 10);

INSERT INTO PERFIL_ACCION (NCODPERFIL_ACCION, NCODPERFIL, NCODSISTEMA, NCODACCION_FORMULARIO)
VALUES (300, 1, 46, 9);

INSERT INTO PERFIL_ACCION (NCODPERFIL_ACCION, NCODPERFIL, NCODSISTEMA, NCODACCION_FORMULARIO)
VALUES (301, 1, 46, 35);

INSERT INTO PERFIL_ACCION (NCODPERFIL_ACCION, NCODPERFIL, NCODSISTEMA, NCODACCION_FORMULARIO)
VALUES (302, 1, 46, 68);

INSERT INTO PERFIL_ACCION (NCODPERFIL_ACCION, NCODPERFIL, NCODSISTEMA, NCODACCION_FORMULARIO)
VALUES (303, 1, 46, 67);

INSERT INTO PERFIL_ACCION (NCODPERFIL_ACCION, NCODPERFIL, NCODSISTEMA, NCODACCION_FORMULARIO)
VALUES (304, 1, 46, 28);

INSERT INTO PERFIL_ACCION (NCODPERFIL_ACCION, NCODPERFIL, NCODSISTEMA, NCODACCION_FORMULARIO)
VALUES (305, 1, 46, 27);

INSERT INTO PERFIL_ACCION (NCODPERFIL_ACCION, NCODPERFIL, NCODSISTEMA, NCODACCION_FORMULARIO)
VALUES (306, 1, 46, 26);

INSERT INTO PERFIL_ACCION (NCODPERFIL_ACCION, NCODPERFIL, NCODSISTEMA, NCODACCION_FORMULARIO)
VALUES (307, 1, 46, 25);

INSERT INTO PERFIL_ACCION (NCODPERFIL_ACCION, NCODPERFIL, NCODSISTEMA, NCODACCION_FORMULARIO)
VALUES (308, 1, 46, 57);

INSERT INTO PERFIL_ACCION (NCODPERFIL_ACCION, NCODPERFIL, NCODSISTEMA, NCODACCION_FORMULARIO)
VALUES (309, 1, 46, 59);

