CREATE TABLE ACCION_FORMULARIO
  (
    NCODACCION_FORMULARIO NUMBER(10) NOT NULL,
    NCODSISTEMA            NUMBER(4) NOT NULL,
    NCODMODULO             NUMBER(10) NOT NULL,
    NCODFORMULARIO         NUMBER(10) NOT NULL,
    VCODPARAMETRO          VARCHAR2(20) NOT NULL,
    NCODIGO                NUMBER(5) NOT NULL,
    NESTADO                NUMBER(4)
  ) ;
  
ALTER TABLE ACCION_FORMULARIO ADD CONSTRAINT SEG_ACCION_FORMULARIO_PK PRIMARY KEY ( NCODACCCION_FORMULARIO ) ;
ALTER TABLE ACCION_FORMULARIO ADD CONSTRAINT MODULO_FORM_FK FOREIGN KEY ( NCODSISTEMA, NCODMODULO, NCODFORMULARIO ) REFERENCES SISTEMA_MODULO_FORM ( NCODSISTEMA, NCODMODULO, NCODFORMULARIO ) ;
ALTER TABLE ACCION_FORMULARIO ADD CONSTRAINT ACC_FORM_SIS_PARAMETRO_FK FOREIGN KEY ( VCODPARAMETRO, NCODIGO ) REFERENCES SISTEMA_PARAMETRO ( VCODPARAMETRO, NCODIGO ) ;


COMMENT ON COLUMN "S_GUIA"."ACCION_FORMULARIO"."NCODACCION_FORMULARIO" IS 'CODIGO DEL REGISTRO ACCION FORMULARIO';
COMMENT ON COLUMN "S_GUIA"."ACCION_FORMULARIO"."NCODSISTEMA" IS 'CODIGO DEL SISTEMA';
COMMENT ON COLUMN "S_GUIA"."ACCION_FORMULARIO"."NCODMODULO" IS 'CODIGO DEL  MODULO';
COMMENT ON COLUMN "S_GUIA"."ACCION_FORMULARIO"."NCODFORMULARIO" IS 'CODIGO DEL FORMULARIO';
COMMENT ON COLUMN "S_GUIA"."ACCION_FORMULARIO"."VCODPARAMETRO" IS 'CODIGO DEL PARAMETRO';
COMMENT ON COLUMN "S_GUIA"."ACCION_FORMULARIO"."NCODIGO" IS 'ID DEL REGISTRO PARAMETRO';
COMMENT ON COLUMN "S_GUIA"."ACCION_FORMULARIO"."NESTADO" IS 'ESTADO DEL REGISTRO';


INSERT INTO ACCION_FORMULARIO (NCODACCION_FORMULARIO, NCODSISTEMA, NCODMODULO, NCODFORMULARIO, VCODPARAMETRO, NCODIGO, NESTADO)
VALUES (53, 46, 1, 4, 'ACCIONES', 20, 0);

INSERT INTO ACCION_FORMULARIO (NCODACCION_FORMULARIO, NCODSISTEMA, NCODMODULO, NCODFORMULARIO, VCODPARAMETRO, NCODIGO, NESTADO)
VALUES (54, 46, 1, 4, 'ACCIONES', 21, 0);

INSERT INTO ACCION_FORMULARIO (NCODACCION_FORMULARIO, NCODSISTEMA, NCODMODULO, NCODFORMULARIO, VCODPARAMETRO, NCODIGO, NESTADO)
VALUES (63, 46, 1, 7, 'ACCIONES', 20, 1);

INSERT INTO ACCION_FORMULARIO (NCODACCION_FORMULARIO, NCODSISTEMA, NCODMODULO, NCODFORMULARIO, VCODPARAMETRO, NCODIGO, NESTADO)
VALUES (64, 46, 1, 7, 'ACCIONES', 21, 0);

INSERT INTO ACCION_FORMULARIO (NCODACCION_FORMULARIO, NCODSISTEMA, NCODMODULO, NCODFORMULARIO, VCODPARAMETRO, NCODIGO, NESTADO)
VALUES (55, 46, 1, 2, 'ACCIONES', 20, 0);

INSERT INTO ACCION_FORMULARIO (NCODACCION_FORMULARIO, NCODSISTEMA, NCODMODULO, NCODFORMULARIO, VCODPARAMETRO, NCODIGO, NESTADO)
VALUES (56, 46, 1, 2, 'ACCIONES', 21, 0);

INSERT INTO ACCION_FORMULARIO (NCODACCION_FORMULARIO, NCODSISTEMA, NCODMODULO, NCODFORMULARIO, VCODPARAMETRO, NCODIGO, NESTADO)
VALUES (67, 46, 1, 6, 'ACCIONES', 28, 1);

INSERT INTO ACCION_FORMULARIO (NCODACCION_FORMULARIO, NCODSISTEMA, NCODMODULO, NCODFORMULARIO, VCODPARAMETRO, NCODIGO, NESTADO)
VALUES (68, 46, 1, 6, 'ACCIONES', 29, 1);

INSERT INTO ACCION_FORMULARIO (NCODACCION_FORMULARIO, NCODSISTEMA, NCODMODULO, NCODFORMULARIO, VCODPARAMETRO, NCODIGO, NESTADO)
VALUES (120, 46, 1, 4, 'ACCIONES', 30, 1);

INSERT INTO ACCION_FORMULARIO (NCODACCION_FORMULARIO, NCODSISTEMA, NCODMODULO, NCODFORMULARIO, VCODPARAMETRO, NCODIGO, NESTADO)
VALUES (21, 46, 1, 5, 'ACCIONES', 16, 1);

INSERT INTO ACCION_FORMULARIO (NCODACCION_FORMULARIO, NCODSISTEMA, NCODMODULO, NCODFORMULARIO, VCODPARAMETRO, NCODIGO, NESTADO)
VALUES (22, 46, 1, 5, 'ACCIONES', 17, 1);

INSERT INTO ACCION_FORMULARIO (NCODACCION_FORMULARIO, NCODSISTEMA, NCODMODULO, NCODFORMULARIO, VCODPARAMETRO, NCODIGO, NESTADO)
VALUES (23, 46, 1, 5, 'ACCIONES', 18, 1);

INSERT INTO ACCION_FORMULARIO (NCODACCION_FORMULARIO, NCODSISTEMA, NCODMODULO, NCODFORMULARIO, VCODPARAMETRO, NCODIGO, NESTADO)
VALUES (24, 46, 1, 5, 'ACCIONES', 19, 1);

INSERT INTO ACCION_FORMULARIO (NCODACCION_FORMULARIO, NCODSISTEMA, NCODMODULO, NCODFORMULARIO, VCODPARAMETRO, NCODIGO, NESTADO)
VALUES (29, 46, 1, 7, 'ACCIONES', 16, 1);

INSERT INTO ACCION_FORMULARIO (NCODACCION_FORMULARIO, NCODSISTEMA, NCODMODULO, NCODFORMULARIO, VCODPARAMETRO, NCODIGO, NESTADO)
VALUES (30, 46, 1, 7, 'ACCIONES', 17, 1);

INSERT INTO ACCION_FORMULARIO (NCODACCION_FORMULARIO, NCODSISTEMA, NCODMODULO, NCODFORMULARIO, VCODPARAMETRO, NCODIGO, NESTADO)
VALUES (31, 46, 1, 7, 'ACCIONES', 18, 1);

INSERT INTO ACCION_FORMULARIO (NCODACCION_FORMULARIO, NCODSISTEMA, NCODMODULO, NCODFORMULARIO, VCODPARAMETRO, NCODIGO, NESTADO)
VALUES (32, 46, 1, 7, 'ACCIONES', 19, 1);

INSERT INTO ACCION_FORMULARIO (NCODACCION_FORMULARIO, NCODSISTEMA, NCODMODULO, NCODFORMULARIO, VCODPARAMETRO, NCODIGO, NESTADO)
VALUES (9, 46, 1, 2, 'ACCIONES', 16, 1);

INSERT INTO ACCION_FORMULARIO (NCODACCION_FORMULARIO, NCODSISTEMA, NCODMODULO, NCODFORMULARIO, VCODPARAMETRO, NCODIGO, NESTADO)
VALUES (10, 46, 1, 2, 'ACCIONES', 17, 1);

INSERT INTO ACCION_FORMULARIO (NCODACCION_FORMULARIO, NCODSISTEMA, NCODMODULO, NCODFORMULARIO, VCODPARAMETRO, NCODIGO, NESTADO)
VALUES (11, 46, 1, 2, 'ACCIONES', 18, 1);

INSERT INTO ACCION_FORMULARIO (NCODACCION_FORMULARIO, NCODSISTEMA, NCODMODULO, NCODFORMULARIO, VCODPARAMETRO, NCODIGO, NESTADO)
VALUES (12, 46, 1, 2, 'ACCIONES', 19, 1);

INSERT INTO ACCION_FORMULARIO (NCODACCION_FORMULARIO, NCODSISTEMA, NCODMODULO, NCODFORMULARIO, VCODPARAMETRO, NCODIGO, NESTADO)
VALUES (13, 46, 1, 3, 'ACCIONES', 16, 1);

INSERT INTO ACCION_FORMULARIO (NCODACCION_FORMULARIO, NCODSISTEMA, NCODMODULO, NCODFORMULARIO, VCODPARAMETRO, NCODIGO, NESTADO)
VALUES (14, 46, 1, 3, 'ACCIONES', 17, 1);

INSERT INTO ACCION_FORMULARIO (NCODACCION_FORMULARIO, NCODSISTEMA, NCODMODULO, NCODFORMULARIO, VCODPARAMETRO, NCODIGO, NESTADO)
VALUES (15, 46, 1, 3, 'ACCIONES', 18, 1);

INSERT INTO ACCION_FORMULARIO (NCODACCION_FORMULARIO, NCODSISTEMA, NCODMODULO, NCODFORMULARIO, VCODPARAMETRO, NCODIGO, NESTADO)
VALUES (16, 46, 1, 3, 'ACCIONES', 19, 1);

INSERT INTO ACCION_FORMULARIO (NCODACCION_FORMULARIO, NCODSISTEMA, NCODMODULO, NCODFORMULARIO, VCODPARAMETRO, NCODIGO, NESTADO)
VALUES (17, 46, 1, 4, 'ACCIONES', 16, 1);

INSERT INTO ACCION_FORMULARIO (NCODACCION_FORMULARIO, NCODSISTEMA, NCODMODULO, NCODFORMULARIO, VCODPARAMETRO, NCODIGO, NESTADO)
VALUES (18, 46, 1, 4, 'ACCIONES', 17, 1);

INSERT INTO ACCION_FORMULARIO (NCODACCION_FORMULARIO, NCODSISTEMA, NCODMODULO, NCODFORMULARIO, VCODPARAMETRO, NCODIGO, NESTADO)
VALUES (19, 46, 1, 4, 'ACCIONES', 18, 1);

INSERT INTO ACCION_FORMULARIO (NCODACCION_FORMULARIO, NCODSISTEMA, NCODMODULO, NCODFORMULARIO, VCODPARAMETRO, NCODIGO, NESTADO)
VALUES (20, 46, 1, 4, 'ACCIONES', 19, 1);

INSERT INTO ACCION_FORMULARIO (NCODACCION_FORMULARIO, NCODSISTEMA, NCODMODULO, NCODFORMULARIO, VCODPARAMETRO, NCODIGO, NESTADO)
VALUES (25, 46, 1, 6, 'ACCIONES', 16, 1);

INSERT INTO ACCION_FORMULARIO (NCODACCION_FORMULARIO, NCODSISTEMA, NCODMODULO, NCODFORMULARIO, VCODPARAMETRO, NCODIGO, NESTADO)
VALUES (26, 46, 1, 6, 'ACCIONES', 17, 1);

INSERT INTO ACCION_FORMULARIO (NCODACCION_FORMULARIO, NCODSISTEMA, NCODMODULO, NCODFORMULARIO, VCODPARAMETRO, NCODIGO, NESTADO)
VALUES (27, 46, 1, 6, 'ACCIONES', 18, 1);

INSERT INTO ACCION_FORMULARIO (NCODACCION_FORMULARIO, NCODSISTEMA, NCODMODULO, NCODFORMULARIO, VCODPARAMETRO, NCODIGO, NESTADO)
VALUES (28, 46, 1, 6, 'ACCIONES', 19, 1);

INSERT INTO ACCION_FORMULARIO (NCODACCION_FORMULARIO, NCODSISTEMA, NCODMODULO, NCODFORMULARIO, VCODPARAMETRO, NCODIGO, NESTADO)
VALUES (33, 46, 1, 8, 'ACCIONES', 16, 1);

INSERT INTO ACCION_FORMULARIO (NCODACCION_FORMULARIO, NCODSISTEMA, NCODMODULO, NCODFORMULARIO, VCODPARAMETRO, NCODIGO, NESTADO)
VALUES (34, 46, 1, 8, 'ACCIONES', 17, 1);

INSERT INTO ACCION_FORMULARIO (NCODACCION_FORMULARIO, NCODSISTEMA, NCODMODULO, NCODFORMULARIO, VCODPARAMETRO, NCODIGO, NESTADO)
VALUES (35, 46, 1, 8, 'ACCIONES', 18, 1);

INSERT INTO ACCION_FORMULARIO (NCODACCION_FORMULARIO, NCODSISTEMA, NCODMODULO, NCODFORMULARIO, VCODPARAMETRO, NCODIGO, NESTADO)
VALUES (36, 46, 1, 8, 'ACCIONES', 19, 1);

INSERT INTO ACCION_FORMULARIO (NCODACCION_FORMULARIO, NCODSISTEMA, NCODMODULO, NCODFORMULARIO, VCODPARAMETRO, NCODIGO, NESTADO)
VALUES (69, 46, 1, 5, 'ACCIONES', 20, 1);

INSERT INTO ACCION_FORMULARIO (NCODACCION_FORMULARIO, NCODSISTEMA, NCODMODULO, NCODFORMULARIO, VCODPARAMETRO, NCODIGO, NESTADO)
VALUES (70, 46, 1, 8, 'ACCIONES', 20, 1);

