CREATE TABLE SISTEMA_MODULO_FORM
(
  NCODSISTEMA          NUMBER(4) NOT NULL,
  NCODMODULO           NUMBER(10) NOT NULL,
  NCODFORMULARIO       NUMBER(10) NOT NULL,
  VDESCRIPCION         VARCHAR2(40),
  NESTADO              NUMBER(4),
  NCODFORMULARIO_PADRE NUMBER(10),
  NNIVEL_FORMULARIO    NUMBER(2),
  NORDEN_FORMULARIO    NUMBER(2),
  VURL_FORMULARIO      VARCHAR2(200),
  VRESCRE              VARCHAR2(15),
  DFECCRE              DATE,
  VRESACT              VARCHAR2(15),
  DFECACT              DATE
);

ALTER TABLE SISTEMA_MODULO_FORM
ADD CONSTRAINT SIS_MOD_FORM_PK PRIMARY KEY (NCODSISTEMA, NCODMODULO, NCODFORMULARIO);
 
ALTER TABLE SISTEMA_MODULO_FORM
ADD CONSTRAINT SIS_MOD_FORM_SIS_MOD_FK FOREIGN KEY (NCODSISTEMA, NCODMODULO)
REFERENCES SISTEMA_MODULO (NCODSISTEMA, NCODMODULO);


COMMENT ON COLUMN "S_GUIA"."SISTEMA_MODULO_FORM"."NCODSISTEMA" IS 'CODIGO DEL SISTEMA';
COMMENT ON COLUMN "S_GUIA"."SISTEMA_MODULO_FORM"."NCODMODULO" IS 'CODIGO DEL MODULO';
COMMENT ON COLUMN "S_GUIA"."SISTEMA_MODULO_FORM"."NCODFORMULARIO" IS 'CODIGO DEL FORMULARIO';
COMMENT ON COLUMN "S_GUIA"."SISTEMA_MODULO_FORM"."VDESCRIPCION" IS 'DESCRIPCION DEL FORMULARIO';
COMMENT ON COLUMN "S_GUIA"."SISTEMA_MODULO_FORM"."NESTADO" IS 'ESTADO DEL REGISTRO ACCESO';
COMMENT ON COLUMN "S_GUIA"."SISTEMA_MODULO_FORM"."NCODFORMULARIO_PADRE" IS 'CODIGO DEL FORMULARIO PADRE';
COMMENT ON COLUMN "S_GUIA"."SISTEMA_MODULO_FORM"."NNIVEL_FORMULARIO" IS 'NIVEL DEL FORMULARIO';
COMMENT ON COLUMN "S_GUIA"."SISTEMA_MODULO_FORM"."NORDEN_FORMULARIO" IS 'NUMERO DE ORDEN DEL FORMULARIO';
COMMENT ON COLUMN "S_GUIA"."SISTEMA_MODULO_FORM"."VURL_FORMULARIO" IS 'URL DE LA PAGINA DEL FORULARIO';
COMMENT ON COLUMN "S_GUIA"."SISTEMA_MODULO_FORM"."VRESCRE" IS 'USUARIO CREACION DEL REGISTRO';
COMMENT ON COLUMN "S_GUIA"."SISTEMA_MODULO_FORM"."DFECCRE" IS 'FECHA DE CREACION DEL REGISTRO';
COMMENT ON COLUMN "S_GUIA"."SISTEMA_MODULO_FORM"."VRESACT" IS 'USUARIO ACTUALIZACION DEL REGISTRO';
COMMENT ON COLUMN "S_GUIA"."SISTEMA_MODULO_FORM"."DFECACT" IS 'FECHA DE ACTUALIZACION DEL REGISTRO';

  
INSERT INTO SISTEMA_MODULO_FORM (NCODSISTEMA, NCODMODULO, NCODFORMULARIO, VDESCRIPCION, NESTADO, NCODFORMULARIO_PADRE, NNIVEL_FORMULARIO, NORDEN_FORMULARIO, VURL_FORMULARIO, VRESCRE, DFECCRE, VRESACT, DFECACT)
VALUES (46, 1, 3, 'MANTENIMIENTO DE MODULOS', 1, 0, 5, 2, '/MODULO', 'SEGADMIN', SYSDATE, 'SEGADMIN', SYSDATE);

INSERT INTO SISTEMA_MODULO_FORM (NCODSISTEMA, NCODMODULO, NCODFORMULARIO, VDESCRIPCION, NESTADO, NCODFORMULARIO_PADRE, NNIVEL_FORMULARIO, NORDEN_FORMULARIO, VURL_FORMULARIO, VRESCRE, DFECCRE, VRESACT, DFECACT)
VALUES (46, 1, 4, 'MANTENIMIENTO DE FORMULARIOS', 1, 0, 1, 3, '/OPCIONFORM', 'SEGADMIN', SYSDATE, 'SEGADMIN', SYSDATE);

INSERT INTO SISTEMA_MODULO_FORM (NCODSISTEMA, NCODMODULO, NCODFORMULARIO, VDESCRIPCION, NESTADO, NCODFORMULARIO_PADRE, NNIVEL_FORMULARIO, NORDEN_FORMULARIO, VURL_FORMULARIO, VRESCRE, DFECCRE, VRESACT, DFECACT)
VALUES (46, 1, 5, 'MANTENIMIENTO DE PERFILES', 1, 0, 1, 4, '/PERFIL', 'SEGADMIN', SYSDATE, 'SEGADMIN', SYSDATE);

INSERT INTO SISTEMA_MODULO_FORM (NCODSISTEMA, NCODMODULO, NCODFORMULARIO, VDESCRIPCION, NESTADO, NCODFORMULARIO_PADRE, NNIVEL_FORMULARIO, NORDEN_FORMULARIO, VURL_FORMULARIO, VRESCRE, DFECCRE, VRESACT, DFECACT)
VALUES (46, 1, 7, 'MANTENIMIENTO DE PARAMETROS', 1, 0, 1, 6, '/PARAMETRO', 'SEGADMIN', SYSDATE, 'SEGADMIN', SYSDATE);


INSERT INTO SISTEMA_MODULO_FORM (NCODSISTEMA, NCODMODULO, NCODFORMULARIO, VDESCRIPCION, NESTADO, NCODFORMULARIO_PADRE, NNIVEL_FORMULARIO, NORDEN_FORMULARIO, VURL_FORMULARIO, VRESCRE, DFECCRE, VRESACT, DFECACT)
VALUES (46, 1, 2, 'MANTENIMIENTO DE SISTEMSA', 1, 0, 1, 1, '/APLICACIONES', 'SEGADMIN', SYSDATE, 'SEGADMIN', SYSDATE);

INSERT INTO SISTEMA_MODULO_FORM (NCODSISTEMA, NCODMODULO, NCODFORMULARIO, VDESCRIPCION, NESTADO, NCODFORMULARIO_PADRE, NNIVEL_FORMULARIO, NORDEN_FORMULARIO, VURL_FORMULARIO, VRESCRE, DFECCRE, VRESACT, DFECACT)
VALUES (46, 1, 8, 'CAMBIA TU CLAVE', 1, 0, 1, 7, '/CLAVE', 'SEGADMIN', SYSDATE, 'SEGADMIN', SYSDATE);

INSERT INTO SISTEMA_MODULO_FORM (NCODSISTEMA, NCODMODULO, NCODFORMULARIO, VDESCRIPCION, NESTADO, NCODFORMULARIO_PADRE, NNIVEL_FORMULARIO, NORDEN_FORMULARIO, VURL_FORMULARIO, VRESCRE, DFECCRE, VRESACT, DFECACT)
VALUES (46, 1, 6, 'MANTENIMIENTO DE USUARIOS', 1, 0, 1, 6, '/USUARIO', 'SEGADMIN', SYSDATE, 'SEGADMIN', SYSDATE);
  
  
  
  
  