ALTER TABLE S_GUIA.PERFIL_SISTEMA ADD VRESCRE VARCHAR2(15);
ALTER TABLE S_GUIA.PERFIL_SISTEMA ADD DFECCRE DATE;
ALTER TABLE S_GUIA.PERFIL_SISTEMA ADD VRESACT VARCHAR2(15);
ALTER TABLE S_GUIA.PERFIL_SISTEMA ADD DFECACT DATE;

COMMENT ON COLUMN "S_GUIA"."PERFIL_SISTEMA"."VRESCRE" IS 'USUARIO CREACION DEL REGISTRO';
COMMENT ON COLUMN "S_GUIA"."PERFIL_SISTEMA"."DFECCRE" IS 'FECHA DE CREACION DEL REGISTRO';
COMMENT ON COLUMN "S_GUIA"."PERFIL_SISTEMA"."VRESACT" IS 'USUARIO ACTUALIZACION DEL REGISTRO';
COMMENT ON COLUMN "S_GUIA"."PERFIL_SISTEMA"."DFECACT" IS 'FECHA DE ACTUALIZACION DEL REGISTRO';


INSERT INTO PERFIL_SISTEMA (NCODPERFIL, NCODSISTEMA, VDESCRIPCION, VESTADO, VRESCRE, DFECCRE, VRESACT, DFECACT)
VALUES (1, 46, 'ADMINISTRADOR', '1', 'SEGADMIN', SYSDATE, 'SEGADMIN', SYSDATE);
