/*select count(1) from s_guia.accesos --1632104

truncate table accesos_tmp;

drop table accesos_tmp;

CREATE TABLE accesos_tmp AS
SELECT * FROM s_guia.accesos;

select count(1) from accesos_tmp -- 1632104

truncate table s_guia.accesos;

select count(1) from s_guia.accesos



INSERT INTO s_guia.accesos (NCODSISTEMA,VCODUSUARIO,DFECFECHA,NCODIP,NCODAREA,VCODACCESO,VCODINGRESO,NCORRELATIVO)
  SELECT NCODSISTEMA,VCODUSUARIO,DFECFECHA,NCODIP,NCODAREA,VCODACCESO,VCODINGRESO,NCORRELATIVO	
    FROM accesos_tmp;
 
select count(1) from s_guia.accesos ;  
select * from s_guia.accesos ;
    
drop table accesos_tmp;
*/
ALTER TABLE S_GUIA.ACCESOS ADD NESTADO NUMERIC(4);
ALTER TABLE S_GUIA.ACCESOS ADD VRESCRE VARCHAR2(15);
ALTER TABLE S_GUIA.ACCESOS ADD DFECCRE DATE;
ALTER TABLE S_GUIA.ACCESOS ADD VRESACT VARCHAR2(15);
ALTER TABLE S_GUIA.ACCESOS ADD DFECACT DATE;
ALTER TABLE S_GUIA.ACCESOS ADD VTOKEN VARCHAR(250);

COMMENT ON COLUMN "S_GUIA"."ACCESOS"."NESTADO" IS 'ESTADO DEL REGISTRO ACCESO';
COMMENT ON COLUMN "S_GUIA"."ACCESOS"."VRESCRE" IS 'USUARIO CREACION DEL REGISTRO';
COMMENT ON COLUMN "S_GUIA"."ACCESOS"."DFECCRE" IS 'FECHA DE CREACION DEL REGISTRO';
COMMENT ON COLUMN "S_GUIA"."ACCESOS"."VRESACT" IS 'USUARIO ACTUALIZACION DEL REGISTRO';
COMMENT ON COLUMN "S_GUIA"."ACCESOS"."DFECACT" IS 'FECHA DE ACTUALIZACION DEL REGISTRO';
COMMENT ON COLUMN "S_GUIA"."ACCESOS"."VTOKEN" IS 'TOKEN DE LA SESSION INGRESADA';


